import type { Metadata } from "next";
import { ArticleCta, ArticleHero, ArticleLayout } from "../GuideChrome";

export const metadata: Metadata = {
  title: "How to Export a Telegram Chat as JSON",
  description: "Export one Telegram conversation from Telegram Desktop in machine-readable JSON format, with optional stickers and media.",
  alternates: { canonical: "/guides/export-telegram-chat" },
};

const toc = [{ href: "#before", label: "Before you begin" }, { href: "#steps", label: "Export steps" }, { href: "#options", label: "Which options matter" }, { href: "#troubleshooting", label: "Troubleshooting" }];

export default function ExportTelegramChatGuide() {
  return <><ArticleHero kicker="Field note 01 · Export" title={<>How to export a Telegram chat <span className="italic text-accent-lit">as JSON.</span></>} intro="Use Telegram Desktop to turn one conversation into a folder you can inspect, archive, or analyze locally." meta="Updated August 2026 · 5 min read" /><ArticleLayout toc={toc}>
    <section id="before"><h2>Start on a computer.</h2><p className="mt-5">Telegram’s export tool lives in Telegram Desktop—not the mobile or web apps. Install or update the desktop application, sign in, and open the individual conversation you want to export.</p><div className="mt-7 border-l-2 border-accent bg-shade px-5 py-4 text-sm leading-relaxed text-ink/70">Telegram may ask you to confirm a new export from another device. If you have just signed in, it may otherwise impose a 24-hour wait.</div></section>
    <section id="steps"><h2>Five steps, one folder.</h2><ol className="mt-7 border-t border-ink/16">{["Open the one-to-one chat in Telegram Desktop.", "Open the three-dot menu in the top-right corner.", "Choose Export chat history.", "Set Format to Machine-readable JSON.", "Choose a destination, complete the export, and keep the entire resulting folder together."].map((step, index) => <li key={step} className="grid grid-cols-[42px_1fr] gap-4 border-b border-ink/12 py-5"><span className="font-display text-2xl text-accent-deep">{String(index + 1).padStart(2, "0")}</span><span>{step}</span></li>)}</ol><p className="mt-6">Telegram also supports exporting all account data from <strong>Settings → Advanced → Export Telegram data</strong>, but a single-chat export is simpler when you only want to analyze one conversation.</p></section>
    <section id="options"><h2>JSON is the important choice.</h2><p className="mt-5">HTML is designed for reading in a browser. JSON preserves the structured fields software needs: timestamps, senders, message text, media references, and reply relationships.</p><h3 className="mt-9">Media is optional</h3><p className="mt-3">Text analysis does not require downloading every photo and video. Include stickers if you want Telescope to display their artwork; otherwise you can leave large media categories unticked to make the export faster and smaller.</p><h3 className="mt-9">Keep the folder intact</h3><p className="mt-3">Choose the completed export folder rather than moving only <code className="rounded bg-shade px-1.5 py-0.5 font-mono text-sm">result.json</code>. Relative media paths point to files beside it.</p></section>
    <section id="troubleshooting"><h2>If “Export chat history” is missing.</h2><ul className="mt-6 space-y-4 border-t border-ink/14 pt-5"><li><strong>Check the app:</strong> use Telegram Desktop, not Telegram Web or a phone app.</li><li><strong>Update Telegram Desktop:</strong> older versions may not expose the current export interface.</li><li><strong>Wait or confirm:</strong> a fresh desktop sign-in can trigger Telegram’s security delay.</li><li><strong>Check the chat type:</strong> Telescope expects a one-to-one JSON conversation, not a full-account export or group chat.</li></ul><p className="mt-7 text-sm">Telegram documents both individual-chat and full-account exports in its <a href="https://telegram.org/blog/export-and-more" rel="noreferrer">official export announcement</a>.</p></section>
    <ArticleCta title="The folder is the starting point." body="Telescope reads the JSON in your browser and builds the numerical report locally. No account is needed for the local analysis." />
  </ArticleLayout></>;
}
